version: '3'
services:
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    